### ISSUE TITLE
Problem with file "Day16_CycleSort.pdf"

### ISSUE THREAD

**Issue by OmAximani0** [artimanputra/DSA-Notes#3]
### Description of the bug

Hi,
I tried to open the "Day16_CycleSort.pdf" file but there is something wrong with it I can't open it on Github also I tried to download and open but it failed to open. Please check out that file. It seems to be corrupted because it shows file size only 34.7 KB.

### Screenshot

![image](https://user-images.githubusercontent.com/75031769/163714580-32aa55d9-0473-480a-900f-b0940be0211c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artimanputra** [comment]
> ### Description of the bug
> Hi, I tried to open the "Day16_CycleSort.pdf" file but there is something wrong with it I can't open it on Github also I tried to download and open but it failed to open. Please check out that file. It seems to be corrupted because it shows file size only 34.7 KB.
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/75031769/163714580-32aa55d9-0473-480a-900f-b0940be0211c.png)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

hey @OmAximani0 I solved it, and now you can download it.
